version: '3.8'

services:
  php:
    build:
      context: ./php
    container_name: ${COMPOSE_PROJECT_NAME}_php
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
    volumes:
      - ./src:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:stable-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - "80:80"  # <--- WAJIB DIGANTI JADI INI (Jangan sampai masih 8080:80)
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mariadb:10.11
    container_name: ${COMPOSE_PROJECT_NAME}_db
    environment:
      MYSQL_DATABASE: ${PROJECT_NAME}
      MYSQL_ROOT_PASSWORD: p455w0rd
    volumes:
      - ./db/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5