server {
    listen 80;
    listen [::]:80;
    
    # Nginx akan merespon request jika user mengakses salah satu dari domain ini
    server_name proyek.test localhost; 
    
    root /var/www/html/public;
    index index.php index.html;

    # Pengaturan untuk routing Laravel (biar URL cantik/clean)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Pengaturan agar Nginx bisa mengeksekusi file PHP lewat container php
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Keamanan: blokir akses ke file .htaccess (karena ini pakai Nginx, bukan Apache)
    location ~ /\.ht {
        deny all;
    }
}